import { MedicalRecord } from '@/types/medical'

export const mockMedicalRecords: MedicalRecord[] = [
  {
    id: '1',
    recordNumber: 'REC-001',
    classification: 'الفئة أ',
    husbandName: 'أحمد محمد العيسى',
    wifeName: 'فاطمة علي الدعيع',
    patientRelationship: 'الزوجة',
    patientName: 'فاطمة علي الدعيع',
    disease: 'السكري من النوع الثاني',
    doctorName: 'د. عمر فاروق',
    treatmentCost: 750,
    disbursementType: 'شهري',
    recordDate: '2024-06-01',
    lastDisbursementDate: '2024-05-15',
    notes: 'حالة مستقرة، تحتاج متابعة دورية شهرية',
    eligibilityStatus: 'مقبول',
    eligibilityReason: 'تحت حد الصرف الشهري (800 جنية)',
    previousDisbursements: [
      { date: '2024-05-15', amount: 750, type: 'شهري' },
      { date: '2024-04-15', amount: 750, type: 'شهري' },
    ],
  },
  {
    id: '2',
    recordNumber: 'REC-002',
    classification: 'الفئة ب',
    husbandName: 'محمد علي الشمري',
    wifeName: 'عائشة سالم الجابري',
    patientRelationship: 'ابن',
    patientName: 'علي محمد الشمري',
    disease: 'الربو الحساس',
    doctorName: 'د. ليلى حسن',
    treatmentCost: 350,
    disbursementType: 'موسمي',
    recordDate: '2024-06-05',
    lastDisbursementDate: '2024-03-20',
    notes: 'ساعات تنفسية منتظمة، يحتاج أدوية موسمية في فصل الربيع والخريف',
    eligibilityStatus: 'مقبول',
    eligibilityReason: 'مستوفي شروط الصرف الموسمي',
    previousDisbursements: [
      { date: '2024-03-20', amount: 350, type: 'موسمي' },
      { date: '2023-12-15', amount: 350, type: 'موسمي' },
    ],
  },
  {
    id: '3',
    recordNumber: 'REC-003',
    classification: 'الفئة أ',
    husbandName: 'علي محمود العتيبي',
    wifeName: 'نور خالد الحمد',
    patientRelationship: 'الزوج',
    patientName: 'علي محمود العتيبي',
    disease: 'أمراض القلب المزمنة',
    doctorName: 'د. أحمد صالح',
    treatmentCost: 950,
    disbursementType: 'شهري',
    recordDate: '2024-06-10',
    lastDisbursementDate: '2024-05-20',
    notes: 'حالة حرجة جداً، يحتاج الصرف الطاريء والمتابعة المكثفة',
    eligibilityStatus: 'استثناء',
    eligibilityReason: 'حالة حرجة تتطلب استثناء - تجاوز الحد المسموح به',
    previousDisbursements: [
      { date: '2024-05-20', amount: 950, type: 'شهري' },
    ],
  },
  {
    id: '4',
    recordNumber: 'REC-004',
    classification: 'الفئة ج',
    husbandName: 'سالم عمر المطيري',
    wifeName: 'هند إبراهيم الخضيري',
    patientRelationship: 'ابنة',
    patientName: 'ليلى سالم المطيري',
    disease: 'التهاب الجلد التحسسي',
    doctorName: 'د. مريم علي',
    treatmentCost: 250,
    disbursementType: 'موسمي',
    recordDate: '2024-06-15',
    notes: 'حالة بسيطة، تحتاج متابعة بسيطة ودوية موضعية',
    eligibilityStatus: 'مرفوض',
    eligibilityReason: 'المبلغ أقل من الحد الأدنى للصرف (400 جنية للموسمي)',
    previousDisbursements: [],
  },
  {
    id: '5',
    recordNumber: 'REC-005',
    classification: 'الفئة أ',
    husbandName: 'خالد أحمد الجمعة',
    wifeName: 'ريم محمد الدخيل',
    patientRelationship: 'الزوجة',
    patientName: 'ريم محمد الدخيل',
    disease: 'أمراض العيون',
    doctorName: 'د. فهد الحمد',
    treatmentCost: 600,
    disbursementType: 'شهري',
    recordDate: '2024-06-20',
    lastDisbursementDate: '2024-05-25',
    notes: 'تحتاج عملية عيون عاجلة، قيد المراجعة من قبل اللجنة الطبية',
    eligibilityStatus: 'قيد_المراجعة',
    eligibilityReason: 'قيد المراجعة من قبل اللجنة الطبية المتخصصة',
    previousDisbursements: [
      { date: '2024-05-25', amount: 600, type: 'شهري' },
    ],
  },
  {
    id: '6',
    recordNumber: 'REC-006',
    classification: 'الفئة ب',
    husbandName: 'يوسف سلمان النواف',
    wifeName: 'زينب منصور الرشيد',
    patientRelationship: 'أخت',
    patientName: 'جميلة يوسف النواف',
    disease: 'السرطان',
    doctorName: 'د. إبراهيم علي',
    treatmentCost: 1200,
    disbursementType: 'شهري',
    recordDate: '2024-06-22',
    lastDisbursementDate: '2024-05-30',
    notes: 'حالة حرجة جداً وخطيرة، تحت المراقبة المكثفة من اللجنة',
    eligibilityStatus: 'استثناء',
    eligibilityReason: 'حالة مرضية حرجة جداً تتطلب استثناء خاص فوري',
    previousDisbursements: [
      { date: '2024-05-30', amount: 800, type: 'شهري' },
    ],
  },
]
